### ISSUE TITLE
bug：ubuntu下google_fu无法正常工作

### ISSUE THREAD

**Issue by orannnnnnge** [ihacklog/p4davan-fw#101]
---------------------------------------------------------

### 固件版本:10月30号以后版本或许包括9.10版

----------------------------------------------------------

## bug 详情描述：
开启google_fu时，ubuntu 16.04、ubuntu 17.10（仅测试这两版本）出现dns解析错误。表现为解析国内域名正常，国外一级域名正常，子域名无法解析或者很慢。
备注：pc dns会重置为127.0.0.1且手动修改之后无效果

关闭google_fu时，一切正常。pc dns为192.168.6.1

仅ubuntu出现此问题，ios和abdroid正常

## bug 重现具体步骤:

1. xxxxx

2. xxxxx

3. xxxxx

**Comment by orannnnnnge** [comment]
我认为是ubuntu自带的dnsmasq和路由器解析相冲突 但是自己无法解决

**Comment by ihacklog** [comment]
内核版本都不贴出来一下？好意思来报bug?

**Comment by orannnnnnge** [comment]
噗 4.10.0-38-generic ubuntu 16.04.3

**Comment by ihacklog** [comment]
内核的问题。

**Comment by hkbase** [comment]
这是新系统的特性导致的，与灯大的固件无关。
我也在ubuntu17.10 server系统下遇到了此问题，下面贴一个自己解决的过程：
systemctl stop systemd-resolved.service
systemctl disable systemd-resolved.service
rm /etc/resolv.conf
vi /etc/resolv.conf
nameserver 路由器ip

**Comment by hcym** [comment]
我的正常吗，1604和1710用chrome
用opera卡的一笔，莫名其妙，都是一种内核

**Comment by orannnnnnge** [comment]
使用灯大方法完美解决
