### ISSUE TITLE
feature：能否在顶部区域显示WAN口状态？是否连通、ip地址等

### ISSUE THREAD

**Issue by Tulipyun** [ihacklog/p4davan-fw#104]
---------------------------------------------------------

提feature的，请在标题开头加 feature . 并清空本模板的所有内容。

方便快速、全局看到连接情况，谢谢！

**Comment by ihacklog** [comment]
请给出你的设计方案。原有内容放哪里，并给出这样设计的理由 。

**Comment by ihacklog** [comment]
不符合模板，直接关闭。
