### ISSUE TITLE
32M W25Q256 winbond 硬改K2P机器 有一定概率不能软重启的bug

### ISSUE THREAD

**Issue by ihacklog** [ihacklog/p4davan-fw#107]
### 固件版本: K2P-512M_3.4.3.9-099_20171112-1923

----------------------------------------------------------

## bug 详情描述：

机器硬件相关： 512M RAM + 32M W25Q256 闪存

硬改K2P 使用了32M W25Q256 闪存的，有一定的机率不能软重启。

## bug 重现具体步骤:

1. 开机

2. 正常使用1-5分钟

3. 进web 后台 ，点击 重置 nvram 

bug出现有一定的概率，不是100%每次重现。
如果bug没有出现，重现此步骤5 到 10 次左右

### 预期的操作结果：

路由器正常重启，并重置nvram配置。

### 实际的操作结果：

点击重置 nvram 后，路由器无法正常重启，红灯常亮
其下客户端无法上网。也无法理web后台。ssh 也无法登录。

只能手动断电然后重新上电开机。

**Comment by biao007** [comment]
http://m.blog.csdn.net/yubing_615/article/details/52649489
“MT7621完美支持32M SPI Flash(W25Q256) 修复 soft reset fail”似乎是解决方法？

**Comment by ihacklog** [comment]
@biao007  这个不行。padavan没有使用m25p80.  用的是raspi

**Comment by lcckis** [comment]
MX25L25635EMI-12G 这个闪存软重启也有一定几率起不来

**Comment by lcckis** [comment]
我拿newifi3 也是MT7621 512M+ W25Q256 32m闪存 刷了hiboy的padavan固件 软重启能100%成功..... 这个是硬件差异造成的还是hiboy有解决方案？ 这个bug有时候远程需要重启路由器的话还是挺严重的，希望无灯大神能修复下....

**Comment by yangcoolno1** [comment]
我用的是mx2L25645的芯片，随机重启失败，机器红灯常亮
bug 重现具体步骤:

开机

正常使用1-5分钟

进web 后台 ，点击 重新启动
然后就是红灯常亮，不能正常启动，只能断电重启

**Comment by ihacklog** [comment]
换成新编译固件，使用不超过16M的闪存空间。解决。
