### ISSUE TITLE
流量记录相关的配置项没有自动提交到nvram

### ISSUE THREAD

**Issue by solaoxo** [ihacklog/p4davan-fw#108]
### 固件版本:3.4.3.9-099_20171112-1940

----------------------------------------------------------

## bug 详情描述：
20171112-1940版本改变流量记录保存时间，本身默认是一周，改成10分钟后，在没断电或重启这段时间的改变是生效的，如果没有到NVRAM提交，中间断电或者正常重启也是不会保存的，会恢复变成一周的配置。

## bug 重现具体步骤:

1. 开机

2. 进web 后台 ，点击（存储网络流量历史和内部存储）改成10分钟

3.断电或者正常重启

### 预期的操作结果：
意外断电和正常重启（存储网络流量历史和内部存储）应该是10分钟的。
### 实际的操作结果：
意外断电和正常重启（存储网络流量历史和内部存储）是一周的。

**Comment by ihacklog** [comment]
fixed.  padavan 本身的bug.

**Comment by solaoxo** [comment]
灯大的效率真高啊
