### ISSUE TITLE
Force proxy IP set(x.x.x.x/n) 添加无效

### ISSUE THREAD

**Issue by 457992195** [ihacklog/p4davan-fw#11]
## bug 详情描述：
  Google-fu   栏
IP Detection     这个按钮  的网页打不开（配置ok youtube也可以看）
Force proxy IP set(x.x.x.x/n)   添加无效

**Comment by ihacklog** [comment]
新版本编译中。等会重新下载刷

**Comment by ihacklog** [comment]
fixed.
