### ISSUE TITLE
修改脚本保存后生效，但即便执行mtd_storage.sh save，路由重启后脚本依旧被还原

### ISSUE THREAD

**Issue by lpker** [ihacklog/p4davan-fw#115]
### 固件版本:3.4.3.9-099_20171115-0152

----------------------------------------------------------

## bug 详情描述：
修改/etc/storage/dnsmasq/目录下的hosts或dnsmasq.servers或dnsmasq.conf文件后保存，执行 mtd_storage.sh save或在webui中点“应用本页面设置”或管理页面右键按钮软重启，重启后文件被还原
## bug 重现具体步骤:

1. 修改 /etc/storage/dnsmasq/目录下的hosts或dnsmasq.servers或dnsmasq.conf文件, 添加自定义的脚本行

2. 在webui点“应用本页面设置”后
ssh、Telnet输入【mtd_storage.sh save】 或
在管理页面点右键按钮软重启

3. 路由重启后，hosts或dnsmasq.servers或dnsmasq.conf文件被还原, 后面添加的脚本行消失

4.双清后重新执行上述步骤，重启后文件依旧被还原

### 预期的操作结果：
路由重启后，自己修改的脚本不被还原

### 实际的操作结果：
在webui修改后，路由重启前，添加的脚本生效；
为了保存修改过的脚本，执行mtd_storage.sh save（或管理页面右键按钮软重启）；
路由重启后, 添加的脚本行消失，修改的内容被还原

**Comment by ihacklog** [comment]
请给一下`time mtd_storage.sh save` 命令的结果。

**Comment by ihacklog** [comment]
我觉得，你可能进错路由了。
3.4.3.9-099_20171115-0152 的固件 ，别说是在后台改的配置，
就算你改完不是软重启，直接断电。丢失文件的概率也是非常小。

**Comment by ihacklog** [comment]
ps: storage的功能，测试过很多次。确认正常。

**Comment by ihacklog** [comment]
目前，mtd_storage.sh save 的执行与不执行。都没有关系。

**Comment by lpker** [comment]
执行完time mtd_storage.sh save的结果：
real	0m 0.01s
user	0m 0.01s
sys	0m 0.00s

**Comment by lpker** [comment]
呃，我也很纳闷，不管咋搞改完重启文件就被重写，路由是k2p的a1银色版没有动过硬件，版本确实是3.4.3.9-099_20171115-0152（上一版固件也是重启文件就还原，所以才升的最新版），用的OpBoot 1.0.6刷的

**Comment by ihacklog** [comment]
能否teamviewer 远程 看看。

**Comment by lpker** [comment]
额，怎么把teamviewer的id和密码发给你

**Comment by ihacklog** [comment]
问题产生的原因是/etc/storage 没有被正确挂载。
新版本 优化了 storage reset 功能。以后如果遇到/etc/storage 没有被正确挂载，
只需要去后台reset 一下storage.

**Comment by YaYa527** [comment]
灯大，我的B70也有类似的问题，请问@lpker 这个问题当时是怎么解决的？
是
1. mtd_storage.sh reset
2. reboot
就行了吗
这是我的输出：

[B70 /www]# time mtd_storage.sh save
Save storage files to MTD partition "/dev/mtdblock6"
Unlocking 'Storage' ...
Writing from '/tmp/storage.tar.bz2' to MTD 'Storage' ...  [ok]
Done.
real    0m 12.57s
user    0m 11.88s
sys     0m 0.59s

[B70 /etc/storage]# mount
rootfs on / type rootfs (rw)
/dev/root on / type squashfs (ro,relatime)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
usbfs on /proc/bus/usb type usbfs (rw,relatime)
tmpfs on /dev type tmpfs (rw,relatime,size=8k)
tmpfs on /etc type tmpfs (rw,noatime,size=8192k)
tmpfs on /home type tmpfs (rw,relatime,size=1024k)
tmpfs on /media type tmpfs (rw,relatime,size=8k)
tmpfs on /mnt type tmpfs (rw,relatime,size=8k)
tmpfs on /tmp type tmpfs (rw,relatime,size=32768k)
tmpfs on /var type tmpfs (rw,relatime,size=4096k)
devpts on /dev/pts type devpts (rw,relatime,mode=600)

[B70 /etc/storage]# cat /proc/mtd
dev:    size   erasesize  name
mtd0: 00040000 00020000 "Bootloader"
mtd1: 00040000 00020000 "BootEnv"
mtd2: 00080000 00020000 "Config"
mtd3: 00040000 00020000 "Factory"
mtd4: 00180000 00020000 "Kernel"
mtd5: 01e80000 00020000 "RootFS"
mtd6: 00400000 00020000 "Storage"
mtd7: 05a40000 00020000 "RWFS"
mtd8: 02000000 00020000 "Firmware_Stub"


我是修改了/etc/storage/shadowsocks_script.sh里的某些行，重启后脚本被还原。

**Comment by ihacklog** [comment]
@YaYa527  B70不要来这里发。这是K2P的，你的B70  压缩不存在K2P有的这个功能。完全不是一回事。
你的脚本被还原也是正常的。
