### ISSUE TITLE
K2P:2.4G频宽无法单独设置成20MHz

### ISSUE THREAD

**Issue by 289699522** [ihacklog/p4davan-fw#12]
## bug 详情描述：
2.4G wifi频宽设置为20MHz无效，需要同时将2.4G和5GHz都改为20MHz才生效。

## bug 重现具体步骤:

1. xxxxx

2. xxxxx

3. xxxxx

**Comment by 289699522** [comment]
此问题还未得到确认吗？

**Comment by ihacklog** [comment]
mt7615dn 只有一块芯片。mtk驱动就是这样工作的。
