### ISSUE TITLE
去广告插件重启失效

### ISSUE THREAD

**Issue by sunhaitao0824** [ihacklog/p4davan-fw#121]
硬件信息

设备厂商：phicomm

设备具体型号(如psg1218-k2): K2P

设备硬件版本(如A1))：A1

固件版本: 3.4.3.9-099_20171116-0125

bug 详情描述：昨天刷完固件后按坛友提供的方式在计划任务里设置定时重启，今天发现重启后去广告失效，本以为是误改了计划任务的原因，双清重置后发现在WEB管理页面重启去广告也依然失效。具体表现为在日志里显示启动信息，但实际没有去广告效果，最简单的方式测试电脑端打开恩山论坛高恪广告就出来了，手动重启插件清空浏览器缓存进入论坛无广告。

## bug 重现具体步骤:

1. 清除浏览器缓存

2. 重启路由器

3. 打开恩山论坛发现广告

**Comment by sunhaitao0824** [comment]
另大神我的固件是昨天用BREED恢复公版分区后从OP刷过来的最新固件

**Comment by ihacklog** [comment]
Filter Ports:  80,443

Log Level 调成debug


再打开视频网站或有广告的页面，比如youku 之类的

```
Nov 17 14:
18:31 koolproxy[26942]: 151.101.72.188:443 transfer to 192.168.6.137:38654 response send size:1428
```

如果能看到类似的日志，说明kp工作正常。

**Comment by sunhaitao0824** [comment]
重新开关KP后有大神提到的日志信息，去广告生效，另ADBYBY一直提示[adbyby]: adbybyfirst.sh连接不上服务器 规则更新不了，等可以连接尝试后再来反馈，打扰大神，感谢大神的付出，谢谢！
![image](https://user-images.githubusercontent.com/32448115/32949463-e1e2b232-cbdd-11e7-8de6-cd971e887c0a.png)
![image](https://user-images.githubusercontent.com/32448115/32949474-ec17682e-cbdd-11e7-8740-29f38942172c.png)

**Comment by luchenhao** [comment]
问一下灯大，我昨天刚刷的最新版 a2 k2p，那个adbyebye显示成功连接服务器，但规则就是不更新。
小飞机也开了，用的是chnroute模式，规则一直显示是2016-1-5 21:45:03 这个时间，开了adbyebye优酷都没法用。

**Comment by ihacklog** [comment]
@sunhaitao0824  测试OK的话，就可以关闭debug。不然写太多日志了

**Comment by sunhaitao0824** [comment]
重启之后去广告是失效的 要重新开关KP才有这个日志啊

**Comment by cc150** [comment]
log level 调成debug,重启后没有kp去广告之类的拦截信息,大神说的有error改成debug本身就是对kp的重启,和关闭KP再打开KP生效的作用是一样的.
