### ISSUE TITLE
灯大，K2P固件能否加个迅雷快鸟

### ISSUE THREAD

**Issue by hbxggf** [ihacklog/p4davan-fw#122]
### 固件版本:K2P_3.4.3.9-099_20171116

----------------------------------------------------------

灯大，是否能在下一版本固件中加入迅雷快鸟，手动不知道怎么加入快鸟插件，谢谢，辛苦了，设备是K2P A2 128M原版的

**Comment by ihacklog** [comment]
duplicate with #7
