### ISSUE TITLE
feature 希望K2 256M的固件加上USB

### ISSUE THREAD

**Issue by biao007** [ihacklog/p4davan-fw#123]
希望K2 256M的固件能把USB的功能加上去，应该一般改256的都会把USB一起改吧，我个人主要把USB用来共享打印机，谢谢！

**Comment by qgtxqj** [comment]
支持一下，也有这个需求。

**Comment by ihacklog** [comment]
改的人很少啊。

**Comment by biao007** [comment]
应该还是不少的，只是之前一直用论坛其他的版本，不过那些版本功能比较少，也很久不更新了。如果你能顺手编译一个版本那就最好了，还有9月11号那个K2－256的版本好像这是搜不到5G信号，试着刷了论坛好几个其他版本的固件都会有这个问题，我大概搜索了一下论坛，应该是从8月左右开始的padavan源代码就会出现5G搜不到和中继连不上的问题的。

**Comment by skychelsea** [comment]
只需要更新128M和512M的即可，要么闪存和内存一起改，要么不改，这两种最多。
