### ISSUE TITLE
bug：k2p刷了最新固件1112版本，网络监控摄像头会自动掉线

### ISSUE THREAD

**Issue by zhang8686** [ihacklog/p4davan-fw#124]
---------------------------------------------------------

### 设备厂商：
斐讯
### 设备具体型号(如psg1218-k2):
k2p
### 设备硬件版本(如A1))：
A1 32+512+usb
### 固件版本:
3.4.3.9-099_20171112-1923
----------------------------------------------------------

## bug 详情描述：
家里用的是中兴-小兴看看网络摄像头，网络连接方式是走Wi-Fi 2.4g，平时用来看孩子的，以前的固件没什么问题，从不会自动掉线。用了最新固件，摄像头连接不到24必自动掉线，查看路由连接设备看不到摄像头这个设备。原先怀疑摄像头问题，把摄像头重置设置后重新连接路由，结果还是一样，不到24小时又掉线了，查看网络日子也看不到什么记录。怀疑是固件问题。固件是直接从910版本升级到1112，升级完，路由也双恢复过设置了。请无灯大大查找下bug原因，尽快修复。

## bug 重现具体步骤:

1. xxxxx

2. xxxxx

3. xxxxx

**Comment by qgtxqj** [comment]
不算bug，Roaming Assistant（漫游助手）的锅。更新到最新1117版本吧，默认漫游助手是关闭的

**Comment by ihacklog** [comment]
@qgtxqj  的回答正确。
