### ISSUE TITLE
BUG:K2P打开Enable Implicit BEAMFORMING后 无法连上WIFI 拔电重启后才正常

### ISSUE THREAD

**Issue by maxiaofeng882** [ihacklog/p4davan-fw#126]
### 固件版本:3.4.3.9-099_20171116-0125

----------------------------------------------------------

## bug 详情描述：
2.4和5G无线打开Enable Implicit BEAMFORMING后 手机和平板均无法连上。关闭和软重启均无效。拔电后重启回复正常。

## bug 重现具体步骤:

1. xxxxx

2. xxxxx

3. xxxxx

**Comment by ihacklog** [comment]
只能说你的手机和平板都有问题。经测试完全正常。测试手机：6s
