### ISSUE TITLE
11.16版K2P，还是不能更新adbyby规则

### ISSUE THREAD

**Issue by mjyhj** [ihacklog/p4davan-fw#129]
---------------------------------------------------------

### 固件版本:3.4.3.9-099_20171116-0125

----------------------------------------------------------

## bug 详情描述：
浏览器不手动点一次，还是不能更新adbyby规则
重启多次adbyby均无效

/tmp/fuck_jdfw.txt
`<html><body><script>var pk="/",qk="u7jo1",tk,rk=new Array(),sk;function nk(ok){for(tk=0;tk<sk.length;tk++)rk[tk]=sk.charCodeAt(tk);tk=50;for(;tk>=3;){rk[tk]=(~(((rk[tk]^169)-228)&0xff))&0xff;tk--;}tk="for(tk=2;tk<=49;){rk[tk]=((((((~rk[tk])&0xff)<<2)&0xff)|(((~rk[tk])&0xff)>>6))+19)&0xff;tk++;}";eval(tk);tk="tk=49;while(true){if(tk<4)break;rk[tk]=(((-((rk[tk]-rk[tk-1])&0xff))&0xff)>>3)|((((-((rk[tk]-rk[tk-1])&0xff))&0xff)<<5)&0xff);tk--;}";eval(tk);sk="";for(tk=1;tk<rk.length-1;tk++)if(tk%8)sk+=String.fromCharCode(rk[tk]^ok);eval("tk=eval");tk(sk);}sk="\xb6\xfbK~\xaf\x97/\xe8\xaf\xed\xd5u\xa8\xe6*\x12\xfb%\x80\xc6v9\x9a\xd6\x1fT\x82&t\xa3c,0b\xa5\r\xbe\xec\xc6\x1e\x11@\xfc\xc0\xef9\x9aM\xf6\nU6";nk(140);</script><script>var u=2;for(;u==1;u++);</script><br><br><br><center><h3><p>访问本页面，您的浏览器需要支持JavaScript</p></h3></center></body></html>
`

**Comment by ihacklog** [comment]
看上去是这段js解密失败了。

**Comment by aylz10** [comment]
添加计划任务（Crontab）每天4:30自动执行脚本
30 4 * * * /etc/storage/adb/adb.sh
将下面脚本保存到 /etc/storage/adb/adb.sh赋予执行权限，

#!/bin/sh



#adbyby规则路径
adbybypath=/etc/storage/adb/data
#adbyby 重新启动命令
adbybyshell=/sbin/restart_adbyby


rm -f /tmp/lazy.txt
echo "正在下载adbyby规则"
logger -t "adbyby规则自定义更新" "正在下载adbyby规则"
wget -P /tmp/ https://raw.githubusercontent.com/adbyby/xwhyc-rules/master/lazy.txt
adbyby1md5=$(md5sum /tmp/lazy.txt | cut -d' ' -f1)
#adbyby1md5=$(md5sum /tmp/lazy.txt | awk -F ' ' '{print $1}')
echo $adbyby1md5
logger -t "adbyby规则自定义更新" "$adbyby1md5"
adbyby2md5=$(md5sum $adbybypath/lazy.txt | cut -d' ' -f1)
#adbyby2md5=$(md5sum $adbybypath/lazy.txt | awk -F ' ' '{print $1}')
echo $adbyby2md5
logger -t "adbyby规则自定义更新" "$adbyby2md5"
echo "检查adbyby规则"
logger -t "adbyby规则自定义更新" "检查adbyby规则"
if [ "$adbyby1md5" = "" ];
then
echo "adbyby规则下载失败，更新脚本退出"
logger -t "adbyby规则自定义更新" "adbyby规则下载失败，更新脚本退出"
else if [ "$adbyby1md5" = "$adbyby2md5" ];
	then
	rm -f /tmp/lazy.txt
	echo "adbyby规则不需要更新，更新脚本退出"
	logger -t "adbyby规则自定义更新" "adbyby规则不需要更新，更新脚本退出"
	else
	echo "正在更新adbyby规则，并重启服务"
	logger -t "adbyby规则自定义更新" "正在更新adbyby规则，并重启服务"
	mv -f /etc/storage/adb/data/lazy.txt /etc/storage/adb/data/lazy.bak
	mv -f /tmp/lazy.txt /etc/storage/adb/data/lazy.txt
	$adbybyshell
	echo "更新完毕"
	logger -t "adbyby规则自定义更新" "更新完毕"
	fi
fi
