### ISSUE TITLE
[ddns]dnspod更新ip后的dns问题

### ISSUE THREAD

**Issue by JimLee1996** [ihacklog/p4davan-fw#13]
## 设备厂商（如联想、netgear）：
斐讯

## 设备具体型号(如psg1218-k2):
psg1218-k2

## 设备硬件版本(如v2))：
a6

## 固件产品ID（如NEWIFI-Y1):
PSG1218-K2

## 固件版本（如3.4.3.9-099_20170905-1100):
3.4.3.9-099_20170911-0050

## bug 详情描述：
灯大ddns中添加了dnspod的功能非常好用。IP更新的很及时，dnspod上更新后的IP也和路由的公网IP一致。但是有一个小问题（可能是dns缓存造成的），因为电脑使用的是路由器提供的dns，所以导致域名对应的IP一直为更新前的IP。过了大概一晚上（约9个小时）还是这样。

## bug 重现具体步骤:

1. 重启设备

2. 等待ddnspod自动更新

3.  dns缓存未刷新导致路由器下级设备域名查询指向老IP

### 操作预期的结果：
在一定时间内（通常是一个小时），域名查询为最新IP

### 操作实际的结果：
过了很长时间，dnspod上更新成功，但本地dns还有问题

**Comment by ihacklog** [comment]
固件设置的适合天朝国情的， dnsmasq 默认 1 小时缓存。
你可以添加dnsmasq 选项，指定你的域名直接经过外网dns查询，而不是缓存。

**Comment by hkbase** [comment]
在LAN--DHCP服务器-- "dnsmasq.servers"的配置里，增加一行
`server=/你的ddns域名A/你的DDNS域名B/119.29.29.29`
这样你的DDNS域名就不会受到本地缓存的影响了。
