### ISSUE TITLE
询问：斐讯K2P有MAC地址过滤和访客网络限速不？

### ISSUE THREAD

**Issue by 1990chs** [ihacklog/p4davan-fw#133]
硬件信息

设备厂商：斐讯

设备具体型号(如psg1218-k2):K2P

设备硬件版本(如A1))：A2

固件版本:K2P_V22.6.6.57官改版
请问是否支持MAC地址过滤以及访客网络限速呢？
官改版自带Opboot，是否可以直接刷此版本固件？

**Comment by 1990chs** [comment]
刷机后发现有这些功能，只是插件的英文的，能不能汉化呢 ？

**Comment by wwwlenovo** [comment]
Please close this issue.

**Comment by ihacklog** [comment]
单IP限制，自己用tc 命令搞定就行。目前无此功能。
