### ISSUE TITLE
bug: 路由重启后自定义的脚本丢失(已解决)

### ISSUE THREAD

**Issue by iHandle** [ihacklog/p4davan-fw#136]
### 固件版本: 3.4.3.9-099_20171116-0125

----------------------------------------------------------

## bug 详情描述：

添加自定义脚本脚本并保存后, 如果重启路由器, 脚本会丢失

## bug 重现具体步骤:

1. 在“运行路由器启动后”初添加自定义脚本并保存

2. 重启路由器

3. 再次回到添加脚本处检查

### 预期的操作结果：
    可以看到自己添加的脚本

### 实际的操作结果：
    自己添加的脚本丢失了

另外,我发现上传到路由到文件在重启后也会丢失, 例外我上传mentohust到 /etc下, 重启后会丢失

###更新
  脚本丢失的解决方法: 如@cuteribs所说, 对路由进行双清后即可解决.(双清方法: 进入路由器后台: 系统管理->恢复/导出/上传设置 两个红色的“重置”按钮都按一次.)
  
  文件丢失的解决办法: padavan只有/ect/storage 目录下的文件不会在重启之后丢失, 所以把文件放在该目录下即可解决.

**Comment by cuteribs** [comment]
我用1113版或后面的版本也有这个情况, 连修改的crontab也会还原.
例如: 修改crontab启用 3点重启. 到3点重启后crontab又还原了.

**Comment by cuteribs** [comment]
双清后重新配置, 再重启就可以保存了

**Comment by iHandle** [comment]
@cuteribs 请问双清在哪里操作?
