### ISSUE TITLE
K2P无法启动AIRTIME FAIRNESS无线高级功能

### ISSUE THREAD

**Issue by diocat** [ihacklog/p4davan-fw#141]
### 固件版本: 3.4.3.9-099_20171116-0125

----------------------------------------------------------

## bug 详情描述：
无法启动无线高级设置中的AIRTIME FAIRNESS功能，据说能明显改善低信号设备对整个无线网络的延迟影响，很有价值。2.4G和5G的AIRTIME FAIRNESS均无法启动。

## bug 重现具体步骤:

1. 直接进入2.4G/5G的无线高级设置，打开AIRTIME FAIRNESS开关

2. 应用

3. 页面刷新后，AIRTIME FAIRNESS恢复关闭的状态

### 预期的操作结果：
AIRTIME FAIRNESS开关显示关闭状态

### 实际的操作结果：
同上

**Comment by ihacklog** [comment]
OK, 下次更新我看下，可能是有个typo ...

**Comment by LF905** [comment]
K2P-512M
A1
3.4.3.9-099_20171117-2030
也是一样的。
