### ISSUE TITLE
chnrt模式下，内外网都正常，唯独安卓机上不了Play商店（谷歌商店）这个app

### ISSUE THREAD

**Issue by JunFSFC** [ihacklog/p4davan-fw#147]
### 固件版本: 3.4.3.9-099_20171116-0125

----------------------------------------------------------

## bug 重现具体步骤:

1. 用手机打开youtube app，正常

2. 打开网页play.google.com，正常

3. 打开Play商店app，出错[DF-DFERH-01]

4. 全局模式下，全部正常

PS：查询到需强制代理services.googleapis.cn这个域名，因不懂界面添加规则，直接在强制代理IP设置下输入services.googleapis.cn并应用，无效。

![263273802751294664](https://user-images.githubusercontent.com/27272229/33926030-90b4efee-e017-11e7-901a-706c02a759de.png)
![128883124384107160](https://user-images.githubusercontent.com/27272229/33926054-a4295f74-e017-11e7-8960-297a3bc1530e.png)
![555818110061813744](https://user-images.githubusercontent.com/27272229/33926219-3878b3a0-e018-11e7-91eb-47ac41ef8203.png)

**Comment by ihacklog** [comment]
那里不能填写域名。只支持IP
