### ISSUE TITLE
无线漫游备注解释框无法自动跳出

### ISSUE THREAD

**Issue by yangcoolno1** [ihacklog/p4davan-fw#150]
-设备厂商：斐讯k2p

设备具体型号(如psg1218-k2):K2P

设备硬件版本(如A1))：A1

固件版本:512MB版本3.4.3.9-099_20171112-1923

----------------------------------------------------------

## bug 重现具体步骤:

1. 光标放置Roaming Assistant RSSI (dBm)和Roaming Assistant Idle Rate (Kbps

2. 查看解释备注框

### 预期的操作结果：
弹出备注提示框

### 实际的操作结果：

不跳出解释框

**Comment by ihacklog** [comment]
你可能误会了。这里压根没有做 tips popup .所以也不存在跳出。
