### ISSUE TITLE
求灯大能加入迅雷快鸟插件

### ISSUE THREAD

**Issue by lqy1328** [ihacklog/p4davan-fw#153]
### 固件版本:3.4.3.9-099_20171116-0125

----------------------------------------------------------

 详情描述：迅雷快鸟只能在电脑里面加速，不能再全局网络里加速，感觉好可浪费
希望灯大能加入迅雷快鸟插件，给网络加点油！
谢谢

**Comment by ihacklog** [comment]
duplicated
