### ISSUE TITLE
K2P A1版本刷公测版最新固件黑群晖docker迅雷连接异常

### ISSUE THREAD

**Issue by xingtianxixi** [ihacklog/p4davan-fw#156]
### 固件版本: PHICOMM K2P 公测版 3.4.3.9-099_20171116-0125

----------------------------------------------------------

## bug 详情描述：

刷最新公测版固件，黑群晖（版本：DSM 6.1.4-15217 Update 5）中docker迅雷连接服务异常，
部分信息如下：
try again...(has tried 19 time(s)).
getting xunlei service info...
Connecting to 127.0.0.1:9000 (127.0.0.1:9000)
wget: can't connect to remote host (127.0.0.1): Connection refused

换LEDN 的LEDE 7.4.1后正常。

## bug 重现具体步骤:

1. K2P 刷 PHICOMM K2P 公测版 3.4.3.9-099_20171116-0125固件

2. 黑群晖（版本：DSM 6.1.4-15217 Update 5）下启动 yinheli-docker-thunder-xware1容器

3. 查看yinheli-docker-thunder-xware1容器终端机的信息

**Comment by ihacklog** [comment]
> getting xunlei service info...
Connecting to 127.0.0.1:9000 (127.0.0.1:9000)
wget: can't connect to remote host (127.0.0.1): Connection refused

这跟固件 有什么关系？
 
127.0.0.1 是本地环回地址。。。

**Comment by cuteribs** [comment]
直接关吧... 这是迅雷远程服务器问题. 跟127.0.0.1也没关系.
