### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by airjam0415** [ihacklog/p4davan-fw#159]
---------------------------------------------------------

---------------------------------------------------------

### 固件版本: padavan 1116

----------------------------------------------------------

## bug 详情描述：
内部网络，dhcp服务器，手工设置dhcp服务器，选择我家里的一台epson l485打印机
选择已经链接的打印机MAC地址，ip地址，主机名
点击添加
IP地址不能被锁定（比如手工更改绑定地址为当前地址不一样的地址，比如当前为192.168.6.195，我设定绑定为192.168.6.18或者192.168.6.199）
重启路由器，或者重启打印机，仍然重新分配给epson打印机一个非绑定的地址。

## bug 重现具体步骤:

1. xxxxx

2. xxxxx

3. xxxxx

**Comment by biao007** [comment]
你没有启用静态ARP绑定吧？只有ARP绑定之后IP地址才不会被占用。

**Comment by ihacklog** [comment]
所谓的静态IP分配，设定后，下次此机器自动获取时就会分配该IP。
此功能一直正常且百分百保证正常。
至于你在客户端 手动设置的IP，这不是DHCP所能管的。
另外，你的issue 标题不标准。这一点我很有意见，所以，此贴被直接关闭。

**Comment by ihacklog** [comment]
label:"not following template"  。 直接关闭。
