### ISSUE TITLE
Google-fu extension 无法打开google

### ISSUE THREAD

**Issue by onlyone-lee** [ihacklog/p4davan-fw#168]
### 固件版本:

3.4.3.9-099_20171116-0125

----------------------------------------------------------

## bug 详情描述：
开启chnrount模式  

GoogleFu DNS配置默认特殊udp端口 

可以打开twitter blogger 但是google 和youtube 无法打开

**Comment by ihacklog** [comment]
你在讨论的是一个不存在的扩展。
