### ISSUE TITLE
[求固件] 魅族Mini Pro 5G (R13P)

### ISSUE THREAD

**Issue by iamchating** [ihacklog/p4davan-fw#171]
荒野无灯 您好

看您9月份说在做魅族mini pro 5G的固件, 后来就没信了, 请问现在有吗? 哪里能下载到, 谢谢

**Comment by ihacklog** [comment]
固件 有的。这个一直忘记去发布了-_-

**Comment by ihacklog** [comment]
http://files.80x86.io/router/rom/MZ-R13P/MZ-R13P_3.4.3.9-099_20170928-0836.trx

c40d8ef411da20014c10d195326ba5eb  MZ-R13P_3.4.3.9-099_20170928-0836.trx
