### ISSUE TITLE
安全类bug,K2P使用NgrokC远程连接路由器 ,不弹出验证窗口

### ISSUE THREAD

**Issue by xingtongsf** [ihacklog/p4davan-fw#179]
---------------------------------------------------------

### 固件版本:3.4.3.9-099_20171124-0209

----------------------------------------------------------

## bug 详情描述：
我使用K2P,用NgrokC给的域名连接K2P路由器，K2P路由器本身不弹出用户名密码验证窗口，能直接进入路由器页面。

## bug 重现具体步骤:

1. Ngrok网站申请代理，用的http代理方式，用的免费服务器

2. K2P开启Ngrok，端口映射为127.0.0.1，80端口

### 实际的操作结果：
使用分配的域名****.free.ngrok.cc访问路由器，能直接进入路由器页面，不弹出用户名密码验证

**Comment by ihacklog** [comment]
这不是一个bug.
注意不要使用 127.0.0.1 ， 这代表路由器自己。自己请求自己，是不需要认证的。
你应该用192.168.x.1 这种地址。
