### ISSUE TITLE
k2p 2g 和 5g 不能互相ping通的问题

### ISSUE THREAD

**Issue by ihacklog** [ihacklog/p4davan-fw#18]
## bug 详情描述：

k2p 2g 和 5g 不能互相ping通

## bug 重现具体步骤:

1. xxxxx

2. xxxxx

3. xxxxx

**Comment by suomalidehaidao** [comment]
顶起来。是有这个bug

**Comment by ihacklog** [comment]
fixed.  7615DN 驱动的锅。

**Comment by puppywang** [comment]
有可测的版本么，这个问题坑我好久了。。。
