### ISSUE TITLE
[code request] Want to build it myself to add ssr

### ISSUE THREAD

**Issue by kmahyyg** [ihacklog/p4davan-fw#180]
### 固件版本:  Latest Version that I can download

----------------------------------------------------------

您好，很抱歉打扰。希望您可以开放一下k2p的本rom的源码，这样我可以在您的基础上添砖加瓦，您不方便添加ssr的话，我想我可以自己添加之后自己编译使用，非常感谢。

**Comment by ihacklog** [comment]
sorry, currently ,no public code available.
maybe someday, I don't know.
