### ISSUE TITLE
网速受到路由限制，不能满速

### ISSUE THREAD

**Issue by AyaWenRen** [ihacklog/p4davan-fw#186]
### 固件版本: 3.4.3.9-099_20171117-2030
----------------------------------------------------------

## bug 详情描述：

电脑直连光猫可跑满网速，路由拨号网速下降至50兆宽带水平

## bug 重现具体步骤:

硬件：千兆光猫，超六类网线，千兆网卡，联通200兆宽带、K2P-512

1、光猫直连电脑，电脑拨号，观察网速。
2、光猫桥接路由，路由拨号，观察网速。
3、光猫桥接路由，路由拨号，关闭路由所有插件功能，观察网速。
4、光猫桥接路由，双清路由，路由拨号，观察网速。

### 预期的操作结果：

四种场景网速表现应为一致。

### 实际的操作结果：

场景1：迅雷下载、测速网站、115下载、网页下载，速度表现一致，200兆宽带跑满。
场景2：迅雷下载200兆宽带跑满，测速网站、115下载、网页下载为50兆宽带水平。
场景3：迅雷下载200兆宽带跑满，测速网站、115下载、网页下载为50兆宽带水平。
场景4：迅雷下载200兆宽带跑满，测速网站、115下载、网页下载为50兆宽带水平。

**Comment by lcckis** [comment]
这种问题就不要发啦，多想想其他人为什么没这种故障

**Comment by ihacklog** [comment]
我不觉得这是固件的问题。
另外 ，注意看下你开了QOS没有。

**Comment by AyaWenRen** [comment]
灯大，我双清过后什么都不开，也是这种情况。默认QOS 是没打开的吧？
在情况四中，我已经详细描述了，是双清过后什么都没开，仅拨号时的测速状况。
这么就关闭了我不服啊

**Comment by lcckis** [comment]
为什么你一定要认为是固件的问题，不在其他地方找问题呢？  你可以光猫拨号测速，或者是更换固件再测啊，固件出问题明显不怎么可能

**Comment by AyaWenRen** [comment]
@lcckis 你倒是给了我一个解决的思路，今天试了一下openwrt cc，问题解决了。只能先放弃老毛子了，等灯大更新下一个版本再回来试试

**Comment by AyaWenRen** [comment]
@ihacklog @lcckis [https://bitbucket.org/padavan/rt-n56u/issues/486/pppoe-slow-download-speed](url)
找到问题在哪里了。固件默认mtu值1492，我测了一下，电脑直连光猫mtu小于等于1452时才能ping通，所以路由设置mtu为1480（1452+28），然后所有问题都解决了
