### ISSUE TITLE
feature 在更新Chnroute时关闭md5校验

### ISSUE THREAD

**Issue by Genkin** [ihacklog/p4davan-fw#187]
### 固件版本:3.4.3.9-099_20171124-0209

----------------------------------------------------------

## bug 详情描述：
更换一下不提供md5sum的Chnroute Update Url后更新时system log出现

> Mar 11 [shado] chnroute.txt: start downloading ...
 chnroute.txt: download md5sum exit code: 1
 chnroute.txt: download md5sum fail.

预期的操作结果：
因为Chnroute Update Url往往都支持https，可以考虑去除md5验证

**Comment by ihacklog** [comment]
这个md5文件 就是用Linux下面的md5sum 生成的。文件名就是chnroute 文件后面加上 .md5sum.txt 后缀。
如原文件为 a.txt , 则校验文件名为： a.txt.md5sum.txt

**Comment by Genkin** [comment]
对不起，应该是我表述不清晰。
路由器自带的Chnroute Update Url长久不更新了，自定义地址诸如https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt
就会因为没有md5sum出现更新失败，就是下面这个提示

> chnroute.txt: download md5sum fail.

有没有可能把验证md5sum的步骤去除呢？

**Comment by Genkin** [comment]
@ihacklog 而类似的操作在自定义fwlist Update Url就不会出现download md5sum fail。我认为这是因为它在更新时没有验证md5sum

**Comment by Genkin** [comment]
这样的需求来源于我要回国加速的想法。如果不可能的话能否把存储Chnroute.txt的目录告诉我，我可以自行替换

**Comment by ihacklog** [comment]
前面的回复我已经告诉你规则了。你完全可以自建 url.

**Comment by Genkin** [comment]
好的，
