### ISSUE TITLE
请荒大更新下16M闪存+128M内存USB版本的K2P

### ISSUE THREAD

**Issue by skychelsea** [ihacklog/p4davan-fw#190]
**硬件信息
设备厂商： PHICOMM
设备具体型号(如psg1218-k2): K2P
设备硬件版本(如A1))： A2
固件版本: 3.4.3.9-099_20170910-2323**
--
**bug 详情描述：**

K2P 16M-128M内存带USB版本，很久没有更新了，请更新一下。
鄙人需要使用无线共享打印和文件共享，仅安装了USB，没有风焊枪对内存和闪存进行升级，也无升级必要。
在5G和2.4G下是无法互通的，无USB版本已改善，请将带USB版本更新下。谢谢

**bug 重现具体步骤:**
开机即可。

**预期的操作结果：**
能将K2P 128M内存带USB版本升级至当前无USB版本最新版本即可。

**实际的操作结果：**
在5G和2.4G下是无法互通。

**Comment by ihacklog** [comment]
已经更新。请在后台升级，或下载  http://files.80x86.io/router/rom/K2P-USB/K2P-USB_3.4.3.9-099_20180402-0735.trx
