### ISSUE TITLE
关于新版storage机制停电有概率丢storage问题

### ISSUE THREAD

**Issue by 289699522** [ihacklog/p4davan-fw#192]
### 固件版本:K2P_3.4.3.9-099_20171116-0125

----------------------------------------------------------

## bug 详情描述：
K2P新版storage机制偶尔会出现意外停电后，storage分区被清空（和重置/etc/storage效果一样）的情况。
大概停十几次电会出现一次（老小区，线路老化，经常停电），一个月丢了三次storage，期间重刷过，也双清过。最后换回旧版 3.4.3.9-099_20171105-0423 固件，到现在两个月未出现丢storage情况。
--

## bug 重现具体步骤:

1. 某次停电，复电后

2. 发现storage分区被清空了……

### 预期的操作结果：
storage分区文件未被清空

### 实际的操作结果：
storage分区文件被清空了

**Comment by 289699522** [comment]
个人看法，storage还是用padavan传统的机制更稳定……

**Comment by ihacklog** [comment]
jffs2 分区比较挑闪存。这一点我也在考虑，是不是要换回来。

**Comment by ihacklog** [comment]
已经换回原来的机制。
