### ISSUE TITLE
bug提出：k2p重启后ss的强制不转发ip规则自动清除

### ISSUE THREAD

**Issue by liuyandashen** [ihacklog/p4davan-fw#194]
### 固件版本:20171116-0125

----------------------------------------------------------

## bug 重现具体步骤:

1. ss的Bypass dst IP/domain 里写几个ip 并保存

2. 重启路由器

3. 再次打开ss的 Bypass dst IP/domain  里面的ip不见了 并且没有绕开填写的ip

### 预期的操作结果：
重启后填写的忽略ip保存下来

### 实际的操作结果：
重启后填写的忽略ip自动清除 没有保存下来

**Comment by ihacklog** [comment]
用了最新版再来反馈。
