### ISSUE TITLE
关于20180321恢复旧版storage机制问题，大于512K内容，storage丢失

### ISSUE THREAD

**Issue by aylz10** [ihacklog/p4davan-fw#196]
硬件信息
设备厂商：斐讯
设备具体型号(如psg1218-k2):K2P-原版
设备硬件版本(如A1))：A1
固件版本:K2P_3.4.3.9-099_20180321-2321
bug 详情描述：
K2P恢复旧版storage机制后，storage分区内容如果大于512K，重启路由后storage分区被清空（和重置/etc/storage效果一样）的情况。使用命令保存失败，提示超出限制大小。
bug 重现具体步骤:
winscp连上路由，在/etc/storage文件夹存放超过512K的文件（空间占用大于512K,小于4M）
使用命令mtd_storage.sh save保存分区
后台手动重启路由

发现storage分区被清空了……

预期的操作结果：
storage分区文件未被清空

实际的操作结果：
storage分区文件被清空了

**Comment by 289699522** [comment]
传统storage机制本身storage容量大小就是512KB。

PS：第一眼看到还以为这是我提的issue……

**Comment by daoxunchen** [comment]
@289699522 那请问有办法在路由器里存放大于512k文件的方法么

**Comment by 289699522** [comment]
@daoxunchen 放在服务器上，WAN上下行启动后 wget 到 tmp 吧。

**Comment by aylz10** [comment]
感觉可以把去广告插件的规则放到tmp里，要不这些规则也占用了storage

**Comment by daoxunchen** [comment]
@289699522 good idea

**Comment by ihacklog** [comment]
放到tmp里也是一个选项。问题是会带来一些不稳定性。

**Comment by aylz10** [comment]
感觉放到tmp里问题应该不大，之前试过A大的官改固件，他的去广告插件实现的方式是：每次开启功能都从web里下载主程序和规则到tmp里，然后执行。当关闭功能以后就删除tmp里的去广告主程序和规则。在使用过程中并没有发现不稳定的情况。
我是觉得灯大可以借鉴下，或者只把规则放到tmp某个文件夹里，在storage里相应目录建个文件夹软连接应该就行了。

**Comment by ihacklog** [comment]
K2P 已经修改为 8M /etc,  2M 的storage, 
保存 文本的话，差不多可以放8M
