### ISSUE TITLE
K2P 2.4G 信道自动选择模式下 5G 信道无法更改

### ISSUE THREAD

**Issue by nuintun** [ihacklog/p4davan-fw#203]
### 固件版本：3.4.3.9-099_20180321-2321

----------------------------------------------------------

## bug 详情描述：

2.4G 无线信道设置为自动选择的时候，5G 无线信道无法更改，被锁定在了 161 信道，选择其它信道不生效（5G 区域代码选择的 china）。

## bug 重现具体步骤:

1. 设置 2.4G 无线信道为自动选择。

2. 更改 5G 信道，用工具查看信道。

### 预期的操作结果：
5G 信道更改为所选信道。

### 实际的操作结果：
5G 信道被锁定在 161。

**Comment by ihacklog** [comment]
两个都设置成手动试试。
疑似为mt7615dn 的特殊问题。
