### ISSUE TITLE
Googlefu如何开启？

### ISSUE THREAD

**Issue by kmahyyg** [ihacklog/p4davan-fw#204]
- [x] 我已查看过去的Issue

### 固件版本:3.4.3.9-099_20180402-0237

----------------------------------------------------------

## bug 详情描述：

根据您官网描述，纸飞机的菜单去哪了？

## bug 重现具体步骤:

1. 打开路由设置界面

### 预期的操作结果：

Extension settings下有Googlefu

### 实际的操作结果：

并没有

需要如何开启？

**Comment by ihacklog** [comment]
如果有一天我不再看github的issue了，可能是因为你这种人。

**Comment by kmahyyg** [comment]
![indexpage.png](https://i.loli.net/2018/04/02/5ac23c4e1eb49.png)
![router page.png](https://i.loli.net/2018/04/02/5ac23c516fcee.png)

图在这里，我按照你的模板填了issue，你官网什么都没有，又挂个ss logo在那里。
路由器里什么都没有，我还是相对客气的请您帮忙解答一下，谢谢。
