### ISSUE TITLE
D1恢复出厂IP地址描述错误，且跳转IP地址错误

### ISSUE THREAD

**Issue by shuaigebo** [ihacklog/p4davan-fw#205]
硬件信息

设备厂商：newifi

设备具体型号(如psg1218-k2): D1

设备硬件版本(如A1))：无

 固件版本:NEWIFI-D1_3.4.3.9-099_20180402-0526.trx

----------------------------------------------------------

bug 详情描述：

D1有个小bug不影响 恢复出厂ip是192.168.99.1你的描述为192.168.6.1也自动跳转到192.168.6.1但是实际应该是192.168.99.1

 bug 重现具体步骤:

1. 点系统管理
2. 点恢复/导出/上传配置
3. 点恢复出厂模式

预期的操作结果：
管理地址描述为192.168.99.1并且恢复结束跳转192.168.99.1
实际的操作结果：
IP地址已经恢复192.168.99.1，但是跳转到了192.168.6.1

**Comment by ihacklog** [comment]
fixed.
