### ISSUE TITLE
恢复出厂时弹出提示IP将恢复成是192.168.6.1但是实际恢复后IP是192.168.2.1

### ISSUE THREAD

**Issue by MayaGates** [ihacklog/p4davan-fw#209]
硬件信息

设备厂商：K2

设备具体型号(如psg1218-k2): K2

设备硬件版本(如A1))：A6

固件版本:PSG1218-K2_3.4.3.9-099_20180402-0630.trx

bug 详情描述：

恢复出厂时弹出提示IP将恢复成是192.168.6.1但是实际恢复后IP是192.168.2.1

**Comment by ihacklog** [comment]
duplicated with #208
