### ISSUE TITLE
K2P padavan 20180402-0237 不兼容虎牙直播app

### ISSUE THREAD

**Issue by shiwuye12** [ihacklog/p4davan-fw#218]
硬件信息

设备厂商：斐讯

设备具体型号(如psg1218-k2): K2P

设备硬件版本(如A1))：A1

固件版本:20180402-0237

----------------------------------------------------------

bug 详情描述：

开启Google-fu后，与虎牙直播app不兼容，首次打开虎牙直播可以正常连接，但第二次打开便无法连接。

bug 重现具体步骤:

1. 使用Google-fu并启动一个有效节点。

2. 在IPHONE上安装虎牙直播app。

3. 打开虎牙直播，并选取一个直播播放半小时，然后退出，重新开启虎牙直播。

预期的操作结果：

可以正常选取直播并正常播放。

实际的操作结果：

几乎无法刷出直播选择菜单。即使刷出，点选后也无法播放。

**Comment by ihacklog** [comment]
虎牙IP段是多少。是不是跑国外段去了

**Comment by shiwuye12** [comment]
这个我不会查。另外，如果关闭Google-fu，开启虎牙直播，还是一样的故障。

**Comment by ihacklog** [comment]
@shiwuye12  关闭之后还是同样的故障。跟它就基本上没关系了。
