### ISSUE TITLE
google-fu无法开启。

### ISSUE THREAD

**Issue by wisedragoncao** [ihacklog/p4davan-fw#22]
## 设备厂商（如联想、netgear）：
斐讯
## 设备具体型号(如psg1218-k2):
k2p
## 固件版本（如3.4.3.9-099_20170905-1100):
3.4.3.9-099_20170910-2246
## bug 详情描述：
google-fu无法开启。

## bug 重现具体步骤:

1. xxxxx
google-fu页面，开启选项点对号，再点击apply，但google-fu并未启动。
2. xxxxx

3. xxxxx

### 操作预期的结果：
希望可以在页面打开google-fu功能

**Comment by ihacklog** [comment]
拒绝回复。固件没有此功能。
