### ISSUE TITLE
k2p的wan口设置中，没有ipv4硬件加速的选项

### ISSUE THREAD

**Issue by waynezwd** [ihacklog/p4davan-fw#224]
# 硬件信息

## 设备厂商：
Phicomm

## 设备具体型号:
K2P

## 设备硬件版本：
A2

## 固件版本:
K2P_3.4.3.9-099_20180402-0237

# BUG详情描述：
外网设置中，wan口选择pppoe拨号，下面没有“IPv4硬件加速”的选择，仅有“QCA SFE加速”的选项，希望能把“IPv4硬件加速”的选项修复上去。
PS：newifi mini和k2，是有“IPv4硬件加速”的选项的。
# bug 重现具体步骤:
1.开机，进入web页面
2.进入外网设置
3.没有“IPv4硬件加速”选项
## 预期的操作结果：
有“IPv4硬件加速”选项。

**Comment by ihacklog** [comment]
MT7615我的固件，都没有HWNAT.  驱动不兼容。去掉了。
