### ISSUE TITLE
K2P A2版本WIFI频繁断流

### ISSUE THREAD

**Issue by gyw00803** [ihacklog/p4davan-fw#225]
### 固件版本:3.4.3.9-099_20180402-0237

----------------------------------------------------------

## bug 详情描述：
使用过程中，WIFI会出现短暂停止响应的问题，症状表现为网页打不开、下载速度变为0，两个频段的WIFI都有此问题。

## bug 重现具体步骤:

1. 此前使用的是K2，没有出现过此问题。

2. 发现K2p的这个问题后，我换回了K2，此问题不再出现。

3. 每次出现的时间大约为不到1分钟，随后网络变为正常，出现的频率大约为每天3次左右。

### 预期的操作结果：
WIFI正常使用，不在出现突然断网的问题。

### 实际的操作结果：
重启无效，回复出厂无效。

**Comment by ihacklog** [comment]
没有断流时的日志？

**Comment by xiaozhangv** [comment]
看一下日志是否有重新拨号pppoe或重新启动wan的日志。应该是连不上网后，重新连接了，也就是重新启动wan了。是否连不上网的标准是下载一个文件是否成功，你用了全部带宽就会卡网，路由器下不了那个文件就认为断网了，就重启了

**Comment by world-soft** [comment]
我的最近也频繁断流

**Comment by gyw00803** [comment]
还有宽带是200m宽带，家里也就是看个高清电视，占不满带宽。。。
