### ISSUE TITLE
Google-fu gfwlist模式无法使用

### ISSUE THREAD

**Issue by lelemka0** [ihacklog/p4davan-fw#226]
### 固件版本:3.4.3.9-099_20180402-0414

----------------------------------------------------------

## bug 详情描述：
将google-fu模式调整为Gfwlist后无法正常工作，Status界面全部ok但总状态为err，log没有显示错误。
SS配置没有问题，白名单模式下可以正常使用。

## bug 重现具体步骤:
修改Google-fu Mode为Gfwlist。

### 预期的操作结果：
状态显示正常且能够正常访问被墙网站。

### 实际的操作结果：
状态显示异常且无法使用。

**Comment by yaoniming-158** [comment]
请允许我也说一句，GFW确实不灵，只能用白名单模式了，就是流量消耗稍微大一些

**Comment by ihacklog** [comment]
无法重现。
