### ISSUE TITLE
强烈建议去除山寨版xfrp替换为正宗的frp

### ISSUE THREAD

**Issue by all85100** [ihacklog/p4davan-fw#227]
硬件信息
设备厂商：斐讯
设备具体型号(如psg1218-k2):k2p
设备硬件版本(如A1))：A1
固件版本:3.4.3.9-099_20180402-0414
bug 详情描述：

xfrp有时无法穿透。重启之后可以穿透,
bug 重现具体步骤:
等待一段时间又无法穿透!

很不稳定,xfrp免费服务器很少,几乎没有!
必须要自己架设!  
没有一点可用性!!!

**Comment by lcckis** [comment]
建议像h大的固件那样，当打开frp功能时才把文件下载到u盘再启动，如果没u盘的加载到内存中来使用...

**Comment by ihacklog** [comment]
frp 的功能，会持续改进的。

**Comment by ihacklog** [comment]
duplicated with #211
