### ISSUE TITLE
MZ-R18 断流无论手机还是电脑基本没网速或者几k，每天必须重启解决问题

### ISSUE THREAD

**Issue by syhandzp** [ihacklog/p4davan-fw#230]
---------------------------------------------------------

提feature的，请在标题开头加 feature . 并清空本模板的所有内容。

提bug的，请务必删除本段提醒文本，没有删除的，直接关闭issue.

提问题之前请先看是否已经有人提出。凡是发现重复提的问题。一律直接关闭。

只留下一句话简单描述的，除非特别明显的问题，否则一律直接关闭和无视。

---------------------------------------------------------

### 固件版本:3.4.3.9-099_20170402-2129

----------------------------------------------------------

## bug 详情描述：
MZ-R18 断流无论手机还是电脑基本没网速或者几k，每天都会出现，每天必须重启解决问题。
之前魅族官方系统没有这种情况。

## bug 重现具体步骤:

1. 晚上八九点出现（排除宽带本身原因）

2. 访问路由器也不可以进入

3. xxxxx

### 预期的操作结果：
重启有时候可以解决问题有时候任然无法解决

### 实际的操作结果：
关掉电源重启

**Comment by syhandzp** [comment]
重复了，不知道怎么删除这个，第一次，大大谅解

**Comment by ihacklog** [comment]
duplicated with #231
