### ISSUE TITLE
（bug）MZ-R18 断流无论手机还是电脑基本没网速或者几k。

### ISSUE THREAD

**Issue by syhandzp** [ihacklog/p4davan-fw#231]
硬件信息

设备厂商：MZ-R18

设备具体型号(如psg1218-k2):MZ-R18

设备硬件版本(如A1))：

固件版本:3.4.3.9-099_20170402-2129

bug 详情描述：

MZ-R18 断流无论手机还是电脑基本没网速或者几k，每天都会出现，每天必须重启解决问题。
之前魅族官方系统没有这种情况。

bug 重现具体步骤:

晚上八九点出现（排除宽带本身原因）

访问路由器也不可以进入

xxxxx

预期的操作结果：

重启有时候可以解决问题有时候任然无法解决

实际的操作结果：

关掉电源重启

**Comment by syhandzp** [comment]
没有使用任何插件，最基本的无线功能，使用一个月一直断流，有时候路由器管理界面都进不去，已经刷回魅族官方固件，希望下个版本可以修复一下谢谢

**Comment by ihacklog** [comment]
没有 硬件。不能确认你说的问题。
这个固件也有一些人在用。但我手里没有硬件。
或许你可以去论坛讨论下吧。找些同在用这个的人。

一般来说不存在这样的问题的。mtk的方案，padavan是成熟的。至少不会像你说的，连界面都登录不去。这在我发布的所有固件中都不存在。
