### ISSUE TITLE
feature K2P 32M硬改的storage，希望能像17年11月版本那样

### ISSUE THREAD

**Issue by Wishing** [ihacklog/p4davan-fw#237]
### 固件版本:

3.4.3.9-099_20180402-0414

## 详情描述：
升级到新版本，storage变得不能装东西了。我是32M版本的，之前能放个8M左右的文件。新版本好像什么都放不下了。。论坛上查了才知道做了改动。
希望能改回之前的版本啊啊啊啊 啊，我实在是需要放点东西进去 啊啊啊啊

**Comment by ihacklog** [comment]
嗯， @qgtxqj  说的是对的。
padavan用的spi驱动是自己改造版的。因此，32M 不能软重启的问题，也不能像openwrt 那样处理。。。
避免不能软重启的唯一办法就是，使用不超过16M的闪存。
