### ISSUE TITLE
feature: openvpn 增加流量混淆补丁 [已实现]

### ISSUE THREAD

**Issue by pupie** [ihacklog/p4davan-fw#242]
源码补丁见：
https://github.com/Tunnelblick/Tunnelblick/tree/master/third_party/sources/openvpn/openvpn-2.4.6/patches

老版本的2.4.x都可以用。针对源码树打补丁即可。

打补丁后可绕过一些防火墙的openvpn协议过滤，此补丁最初源于openvpn论坛，后被此客户端代码审计后集成。
在配置文件中加入：
scramble obfuscate change_to_your_random_string

即可。如不启用此选项，服务器端可和原版官方PC、手机客户端兼容，如启用此选项，客户端也需要打补丁重新编译以支持此参数，并在配置文件中启用相同的参数。

**Comment by pupie** [comment]
帮助文档见：https://tunnelblick.net/cOpenvpn_xorpatch.html

**Comment by ihacklog** [comment]
padavan里面的版本应该 是2017.09.25 -- Version 2.4.4

**Comment by ihacklog** [comment]
可以尝试添加一下。

**Comment by ihacklog** [comment]
xor patch 已经应用，等待测试。

**Comment by ihacklog** [comment]
已添加 http://files.80x86.io/router/rom/K2P/K2P_3.4.3.9-099_20180603-0704.trx

**Comment by ihacklog** [comment]
@pupie 赞。
更新记录里加上这个issue地址了。
http://p4davan.80x86.io/blog/2018/06/05/20180605-padavan-fw-update/
