### ISSUE TITLE
K2P padavan 固件[无线漫游助手+智能连接+MU-MIMO+波束成型刷机后无2.4G无线

### ISSUE THREAD

**Issue by qq24021438** [ihacklog/p4davan-fw#243]
---------------------------------------------------------

### 固件版本:K2P padavan 固件[无线漫游助手+智能连接+MU-MIMO+波束成型

----------------------------------------------------------

## bug 详情描述：
刷机后无2.4G无线，进breed刷其他的固件也没有2.4G了，换OPBOOT刷第三方固件的还是没有，确定硬件没坏

**Comment by ihacklog** [comment]
换其它固件还没有。你来问我？
