### ISSUE TITLE
google-fu原版SS无法使用gcm加密

### ISSUE THREAD

**Issue by Corvus091** [ihacklog/p4davan-fw#245]
### 固件版本:3.4.3.9-099_20180402-0237

----------------------------------------------------------

## bug 详情描述：

google fu原版SS，未设置任何协议和混淆，无法使用aes-256-gcm加密方式访问google

## bug 重现具体步骤:

1. 使用aes-256-cfb 加密帐号可以正常FQ访问google

2. 使用aes-256-gcm 加密帐号无法正常FQ访问google

3. 手机端shadowrocket和pc端Shadowsocks使用aes-256-gcm 加密帐号均可以正常上网，排除帐号问题

### 预期的操作结果：
使用aes-256-gcm 加密帐号正常FQ访问google

### 实际的操作结果：
使用aes-256-gcm 加密帐号无法正常fq访问google

**Comment by ihacklog** [comment]
最新版固件。经测试完全正常。
