### ISSUE TITLE
google-fu游戏模式BUG（xbox）

### ISSUE THREAD

**Issue by hengshan505** [ihacklog/p4davan-fw#28]
## 固件版本（如3.4.3.9-099_20170905-1100):

3.4.3.9-099_20170910-2246
--

## bug 详情描述：
xbox测试网络时会100%丢包，使游戏无法正常联机

## bug 重现具体步骤:

GoogleFu Mode的三种模式都试过（开启UDP Relay，关闭Block webRTC），无法在转发udp的情况下正常使用

1. xxxxx

2. xxxxx

3. xxxxx

### 操作实际的结果：
PS4正常

**Comment by ihacklog** [comment]
需要进一步确认问题。
100%丢包， 是哪个服务器（IP或域名 ），哪个端口

**Comment by gaohaoyuan** [comment]
能告诉我一下，这个Google-fu的混淆协议怎么设置吗？谢谢了
