### ISSUE TITLE
解决内网迅雷下载，无法正常使用的问题

### ISSUE THREAD

**Issue by hkbase** [ihacklog/p4davan-fw#31]
建议路由器hosts内置下列条目：
127.0.0.1 hub5btmain.sandai.net
127.0.0.1 hub5emu.sandai.net
127.0.0.1 upgrade.xl9.xunlei.com
127.0.0.1 liveupdate.mac.sandai.net

**Comment by hkbase** [comment]
hosts加入以上代码后试用，迅雷下载，还是显示文件非法无法下载
![image](https://user-images.githubusercontent.com/9875710/31645302-ea8ae256-b32d-11e7-8592-409b88ebe0c2.png)
暂时无解啊。。。

**Comment by ihacklog** [comment]
代码已经添加。默认为未开启。需要自行取消前面的#.
毕竟这个会影响迅雷程序的更新。并不是每个要想要的。
