### ISSUE TITLE
Kcptun不能从外部连接

### ISSUE THREAD

**Issue by jfc8000** [ihacklog/p4davan-fw#36]
设备厂商：斐讯
设备具体型号:k2p
设备硬件版本(如A1))：A1 银色版
固件版本:K2P 3.4.3.9-099_20170910-2246
bug 详情描述：
K2P padavan 的Kcptun不能从电脑连接 只能使用内置的ss连接
想用路由上的 Kcptun 加速电脑的ss就连不上
netstat 命令查看 路由的Kcptun客户端监听地址是 127.0.0.1 而不是 0.0.0.0
不知道是我设置不正确还是固件本身如此
这个功能还是比较重要的
希望大侠指点

**Comment by ihacklog** [comment]
目前确实是固定监听lo 接口

**Comment by ihacklog** [comment]
后续看能否改进

**Comment by zkname** [comment]
我早发现这个问题了，我是在自定义脚本运行的，真心麻烦啊。

**Comment by pchaos** [comment]
按道理只要把监听的127.0.0.1改成0.0.0.0就好了

**Comment by zkname** [comment]
和ip没有关系的不能选定网卡，写死了 lo 了。

**Comment by ihacklog** [comment]
fixed.
代码已经更新。下一版本会修复
