### ISSUE TITLE
K2P 无线 mac过滤允许模式部分手机连不上

### ISSUE THREAD

**Issue by 302532333** [ihacklog/p4davan-fw#37]
WIFI 2.4G和5G 选mac过滤，开启允许模式，部分列表中的手机连不上，关了过滤就能连上。mac没有填错，检查了好几次。关闭WIFI的MAC过滤，开启防火墙MAC访问限制确无此问题。

**Comment by ihacklog** [comment]
请按模板写详细的重现步骤。

**Comment by ihacklog** [comment]
否则会被直接关闭
