### ISSUE TITLE
灯大好，能否增加一个广东电信家庭云提速功能

### ISSUE THREAD

**Issue by cn5i** [ihacklog/p4davan-fw#40]
---------------------------------------------------------
### 固件版本:

----------------------------------------------------------

一直在用灯大的固件，感谢灯大！
广东电信家庭云上传提速可以到20M，一般需要在app上传时提速，之前H大发布的老毛子中增加了家庭云抓包提速功能，实现路由器端直接提速，H大没有专门的k2p固件。求灯大帮忙增加一个家庭云提速功能，感谢！

**Comment by ihacklog** [comment]
这个要等11月以后再看吧。我这里暂时是100M.没有条件测试。

**Comment by xlpppp** [comment]
主要是提升上传速度，我这里测试是无问题的，广东电信
请求灯大更新添加，以便早上减少辐射，多活几天（现在加多了一台K2路由一起用） ^^!

**Comment by ihacklog** [comment]
等半个月左右。我100M取消了，但是还没有结束。结束后才能测试提速。

**Comment by ihacklog** [comment]
http://files.80x86.io/router/rom/opt/speedup/
不过，我这边没法用了。
