### ISSUE TITLE
酸酸乳？不存在的。不要给我提酸酸乳的问题。

### ISSUE THREAD

**Issue by nigelink** [ihacklog/p4davan-fw#41]
---------------------------------------------------------

feature 请在标题开头加 feature . 并清空本模板的所有内容。

提问题之前请先看是否已经有人提出。凡是发现重复提的问题。一律直接关闭。

只留下一句话简单描述的，除非特别明显的问题，否则一律直接关闭和无视。

---------------------------------------------------------
### 固件版本:0910

----------------------------------------------------------

## bug 重现具体步骤:

1. xxxxx

2. xxxxx

3. xxxxx

**Comment by ihacklog** [comment]
暂时没有添加的计划。

**Comment by cuteribs** [comment]
我也觉得原版功夫就够了, 老大还包含了server, 如果能把server界面加上好了. 目前我只能手动跑server,
