### ISSUE TITLE
feature K2p 0910固件 打开adbyby，防火墙中网址过滤失效 ,DDNS

### ISSUE THREAD

**Issue by sunkima** [ihacklog/p4davan-fw#42]
---------------------------------------------------------
### 固件版本:   0910 

----------------------------------------------------------

## bug 详情描述：

防火墙中网址过滤失效

## bug 重现具体步骤:

1. 通用配置中启用防火墙

2. 添加过滤域名，比如www.baidu.com,并应用配置

3. 访问 www.baidu.com

4、重启路由器，DDNS不更新，失效了。

### 预期的操作结果：
不可访问

### 实际的操作结果：

可以访问

**Comment by ihacklog** [comment]
duplicate with #24

**Comment by sunkima** [comment]
更新了下，ddns也失效，原因好像是不是ss引起的，而是adbyby导致。

**Comment by ihacklog** [comment]
打开adbyby，防火墙中网址过滤失效, 这个一直是这样。以后有时间修复。
还有，不要一个issue提两个问题！！！
