### ISSUE TITLE
5G中继设置好后，路由器重启后无法自动中继

### ISSUE THREAD

**Issue by xz666666** [ihacklog/p4davan-fw#43]
---------------------------------------------------------
### 固件版本:K2P_3.4.3.9-099_20170910-2246

----------------------------------------------------------

## bug 详情描述：
设置好5G中继上级信号后，重启K2P，K2P无法自动中继，需要重新搜索5G信号并进行中继

**Comment by ihacklog** [comment]
访问 http://my.router/Advanced_InetDetect_Content.asp

Perform Action on [Internet Lost] Event:  选择wan reconnect.

**Comment by world-soft** [comment]
灯大，我的问题是用2.4G中继的话，上级路由的信道变更后，k2p(副路由)无法自动跟踪上级信道，会自动断网，必须要在2.4G里重新扫描上级ssid再次应用设置才行。请问怎么可以在不设置上级路由信道为自动选择的情况下，k2p能自动跟踪上级路由？
