### ISSUE TITLE
开机脚本 重启后还原.

### ISSUE THREAD

**Issue by cuteribs** [ihacklog/p4davan-fw#44]
### 固件版本: K2P_3.4.3.9-099_20170910-2246.trx

----------------------------------------------------------

## bug 详情描述：
开机脚本 /etc/storage/started_script.sh 修改后保存再运行没问题. 断电重启后 started_script.sh 还原成修改前的内容了.

## bug 重现具体步骤:

1. 修改 /etc/storage/started_script.sh, 添加自定义的脚本行

2. 重启

3. /etc/storage/started_script.sh 还原, 前面添加的脚本行消失

### 预期的操作结果：
开机后自动执行添加的脚本行.

### 实际的操作结果：
修改的内容被还原, 添加的脚本行未执行

**Comment by ihacklog** [comment]
脚本改了要执行 mtd_storage.sh save 你不知道？

**Comment by cuteribs** [comment]
我是在后台web ui里改的. 发现会还原又ssh进去改还是不行. 910版是需要手机跑一下 mtd_storage.sh吗?

**Comment by ihacklog** [comment]
任何padavan都这样。自己先看点教程吧。

**Comment by ihacklog** [comment]
没有  mtd_storage.sh save 断电必丢。 （点击路由器里的重启会自动执行  mtd_storage.sh save ，因此不用担心这个问题）

**Comment by cuteribs** [comment]
灯大, 我更新了1113版后, 确定自定义脚本重启后会还原..... 手工mtd_storage.sh save后重启也一样.
