### ISSUE TITLE
K2P 512MB Wireless info page 不能显示连接终端

### ISSUE THREAD

**Issue by jelly0925** [ihacklog/p4davan-fw#45]
---------------------------------------------------------

feature 请在标题开头加 feature . 并清空本模板的所有内容。

提问题之前请先看是否已经有人提出。凡是发现重复提的问题。一律直接关闭。

只留下一句话简单描述的，除非特别明显的问题，否则一律直接关闭和无视。

---------------------------------------------------------
### 固件版本:3.4.3.9-099_20170910-2258

----------------------------------------------------------

## bug 重现具体步骤:

1. xxxxx

2. xxxxx

3. xxxxx

**Comment by ihacklog** [comment]
代码已经修复。下一个版本就会是OK的

**Comment by jelly0925** [comment]
辛苦了。
