### ISSUE TITLE
启用 访客AP 时，电脑“网络”无法访问NAS

### ISSUE THREAD

**Issue by xysck** [ihacklog/p4davan-fw#49]
---------------------------------------------------------

feature 请在标题开头加 feature . 并清空本模板的所有内容。

提问题之前请先看是否已经有人提出。凡是发现重复提的问题。一律直接关闭。

只留下一句话简单描述的，除非特别明显的问题，否则一律直接关闭和无视。

---------------------------------------------------------
## 硬件信息
斐讯
### 设备厂商：
斐讯
### 设备具体型号(如psg1218-k2):
k2p
### 设备硬件版本(如A1))：
A1
### 固件版本:
3.4.3.9-099_20170726-2038
---------------------------------------------------------
## bug 详情描述：
电脑通过有线连接到路由器的LAN，电脑系统为win7。当k2p不启用无线访客时，点击“计算机”，在左侧的“网络”下面可以显示出群晖NAS，也可以访问里面的文件及文件夹。但开启无线访客（2.4D\2.5G）时，并设置密码后，无线访客可正常使用，但这时，电脑“网络”下面没有显示NAS了，如果关闭无线访客，又可显示。

## bug 重现具体步骤:

1. 电脑通过有线连接到路由器的LAN

2. 开启无线访客（2.4D或2.5G）

3. 点击桌面的计算机-----左侧”网络‘无法显示NAS

### 预期的操作结果：
建议修复

**Comment by ihacklog** [comment]
我回去 试试看

**Comment by ihacklog** [comment]
应该是ap 隔离开启了。
