### ISSUE TITLE
feature：希望增加给连接设备重命名功能，如果能增加限速更好 

### ISSUE THREAD

**Issue by qyzjj** [ihacklog/p4davan-fw#52]
硬件信息

斐讯

设备厂商：

斐讯

设备具体型号(如psg1218-k2):

k2p

设备硬件版本(如A1))：

A1+usb

固件版本:

3.4.3.9-099_20170910

希望增加给每个连接设备重命名功能最好支持中文，如果能给每连接设备增加限速更好 ！辛苦了，灯大。

**Comment by ihacklog** [comment]
限速 可以用脚本。
重命名暂可能没有计划。
