### ISSUE TITLE
闪讯 v4.x 算法支持计划

### ISSUE THREAD

**Issue by ihacklog** [ihacklog/p4davan-fw#6]
声明：本人不用闪讯。也没有测试闪讯的条件。

考虑到有部分学生朋友会使用这个。因此有了此issue.

目前有部分地区已经不再是用老的v2.x 的算法了。
打算想点办法搞到新算法。

目前找到的可支持v4.x的有：
https://github.com/sunflyer/SimpleNetkeeper

大家有资料也可以提供一下。

**Comment by ihacklog** [comment]
旧算法的相关资料：

综合项目之闪讯破解（一）之 闪讯拨号用户名核心算法
http://blog.csdn.net/qq_33212020/article/details/52972188

**Comment by Destinyzxn** [comment]
dalao可以尝试添加这个 https://github.com/huipengly/Openwrt-NetKeeper/tree/master/netkeeper4-use-pppoer-server 采用截获的办法 获得真实账号 用来拨号

**Comment by ihacklog** [comment]
https://sunflyer.cn/archives/tag/netkeeper

**Comment by ihacklog** [comment]
Netkeeper基本流程分析(旧版本)
https://sunflyer.cn/archives/239

**Comment by ihacklog** [comment]
How To : 从Netkeeper 4.X客户端获取真实账号
https://sunflyer.cn/archives/460

**Comment by ihacklog** [comment]
脑子是个好东西，我希望你们都有
好文章  https://sunflyer.cn/archives/437

**Comment by Destinyzxn** [comment]
dalao有想法集成吗

**Comment by NorthNanmu** [comment]
https://github.com/miao1007/Openwrt-NetKeeper/tree/master/netkeeper4-use-pppoer-server
https://github.com/miao1007/Openwrt-NetKeeper/blob/master/netkeeper4-use-pppoer-server/README.md
闪讯4.X破解基本不存在，但是可以在路由器端建立一个pppoe-server来伪装拨号服务器，拦截到账号后再通过wan口拨号出去（**但是需要路由器支持换行符**）刚刚回复到drcom的issue下去了

**Comment by NorthNanmu** [comment]
另外，需要将里面文件源码中的netkeepee-wan全部替换成wan方能使用

**Comment by ihacklog** [comment]
http://www.right.com.cn/forum/forum.php?mod=viewthread&tid=214612

**Comment by stawidy** [comment]
Padavan上面能架设得了pppoe-server吗

**Comment by ihacklog** [comment]
已经支持拦截 和 老版本的算法。不带心跳的PPPoE拨号通吃。

**Comment by stawidy** [comment]
@ihacklog现在只有k2p的固件支持吗

**Comment by wuchen160** [comment]
辽宁电信用的也是闪讯 无心挑 如何开启固件内PPPoE？？

**Comment by ALazyLeaner** [comment]
无灯老大。pppoe server 在哪啊。我刷了最新的1109版本，里面没找到啊
