### ISSUE TITLE
b70 kp不自动更新了

### ISSUE THREAD

**Issue by 3375967** [ihacklog/p4davan-fw#65]
好多天了一直是这个
Static Rule Update: 
 2017-10-16 22:50
2017-10-16 22:30

-

**Comment by ihacklog** [comment]
这个，我也差点被误导了。实事就，KP就是这么多天没更新了。。。
https://kprules.b0.upaiyun.com/daily.txt
```
!x  -----[KoolProxy Plus 3.6.2]
!x  -----update[rules]: 2017-10-16 22:11
```
