### ISSUE TITLE
feature-ADBYBY更新，能否修改成自定义规则地址

### ISSUE THREAD

**Issue by mjyhj** [ihacklog/p4davan-fw#71]
### 预期的操作结果：
adbyby 添加自定义更新规则地址

### 实际的操作结果：
可以自由选择官网updat.adbyby.com上的规则地址
或者 使用https上的github规则地址
https://raw.githubusercontent.com/adbyby/xwhyc-rules/master/lazy.txt
https://raw.githubusercontent.com/adbyby/xwhyc-rules/master/video.txt
原因最近ISP经常劫持，导致 规则被重定向一个乱码文本

**Comment by ihacklog** [comment]
好像不是劫持。我看了是adbyby加了个什么金盾防火墙

**Comment by mjyhj** [comment]
请问如何自行修改更新规则地址

**Comment by mjyhj** [comment]
原理因为防火墙的原因，必须要用浏览器访问一次，才能正常下载规则

adbyby 规则更新方法
由于规则服务器使用了金盾防火墙防cc、ddos攻击的原因，导致非浏览器链接不会链接到正确内容，测试需在浏览器打开内容一次正常后，如http://update.adbyby.com/rule3/video.txt，就可正常更新了
关于服务器防火墙的技术说明：http://www.piaoyi.org/seo/jindun-jdfwkey.html

那么 padavan上能不能用wget虚拟浏览器来访问
wget --user-agent="Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"  http://update.adbyby.com/rule3/video.txt

**Comment by ihacklog** [comment]
related #59

**Comment by ihacklog** [comment]
防火墙问题已经解决。转移到 #59 讨论吧
