### ISSUE TITLE
5G频段信道修改无效，实际测试一直保持52信道，5G路由模式下不能WDS+AP

### ISSUE THREAD

**Issue by sxlouxinkun** [ihacklog/p4davan-fw#72]
---------------------------------------------------------

feature 请在标题开头加 feature . 并清空本模板的所有内容。

提问题之前请先看是否已经有人提出。凡是发现重复提的问题。一律直接关闭。

只留下一句话简单描述的，除非特别明显的问题，否则一律直接关闭和无视。

---------------------------------------------------------
### 固件版本:3.4.3.9-099_20171030-0324
--

----------------------------------------------------------

## bug 详情描述：
5G频段信道修改无效，实际测试一直保持52信道，路由模式不能WDS+AP

## bug 重现具体步骤:

1. xxxxx

2. xxxxx

3. xxxxx

### 预期的操作结果：
若能修复望修复

**Comment by ihacklog** [comment]
无线的，先等等吧。

**Comment by ihacklog** [comment]
自动 ，还是人工设定，2g, 5g, 两个都改成一样。
