### ISSUE TITLE
首先感谢灯大，再次求助，能否在扩展功能加入VpnProxy端口转发功能！

### ISSUE THREAD

**Issue by jw19891128** [ihacklog/p4davan-fw#73]
---------------------------------------------------------

首先感谢灯大，再次求助，能否在扩展功能加入VpnProxy 虽然现在流量便宜，但是大家都喜欢琢磨的过程，现在免流都用到端口代理功能，VpnProxy在端口转发方面非常的方便，希望灯大能考虑，谢谢

------------------------------------------------------
### 固件版本:20171030

----------------------------------------------------------

## bug 详情描述：

首先感谢灯大，再次求助，能否在扩展功能加入VpnProxy 虽然现在流量便宜，但是大家都喜欢琢磨的过程，现在免流都用到端口代理功能，VpnProxy在端口转发方面非常的方便，希望灯大能考虑，谢谢

**Comment by ihacklog** [comment]
没有研究这个。不太清楚这个东西

**Comment by hkbase** [comment]
@jw19891128 我现在就在用灯大的固件，实现免流。你把vpnproxy程序放进灯大固件里，是可以直接运行，一条命令就能实现的事情，还是不要麻烦灯大了吧。

**Comment by jw19891128** [comment]
@hkbase 文件我有，求具体操作方法，在此谢过，可加我V信58285474交流，再次感谢@hkbase感谢@ihacklog

**Comment by xlpppp** [comment]
可以把文件发上来看看不
