### ISSUE TITLE
1030固件，5G无线手机连接，会偶尔断连

### ISSUE THREAD

**Issue by yehl** [ihacklog/p4davan-fw#74]
### 固件版本:20171030

----------------------------------------------------------

## bug 详情描述：
今天升级1030版本固件，手机连接5G无线，会偶尔断连，今天已经出现4次。0910版本无此问题出现。
升级完固件后，保险起见，我是做了双清工作。

**Comment by ihacklog** [comment]
不存在的事。最新版只可能更稳定。
