### ISSUE TITLE
20171031-0235版本网络流量上下行反了！

### ISSUE THREAD

**Issue by jw19891128** [ihacklog/p4davan-fw#75]
---------------------------------------------------------
20171031-0235版本网络流量上下行反了！

---------------------------------------------------------
### 固件版本:20171031-0235

----------------------------------------------------------

## bug 详情描述：

20171031-0235版本网络流量上下行反了！下面是我上次所提到的 大家都希望您加入的VpnProxy代理功能，这样可代理端口！hiboy的K2固件内有这个功能，希望灯大您借鉴一下，谢谢
![153849lz2zbihbli2pvv1b_](https://user-images.githubusercontent.com/33219436/32200723-0ad4e616-be0e-11e7-9606-ae5e817bd252.png)

**Comment by ihacklog** [comment]
标题和内容不符合，会被直接关闭。
