### ISSUE TITLE
IPTV代理服务器UDP 代理 (Udpxy)无法工作

### ISSUE THREAD

**Issue by Tulipyun** [ihacklog/p4davan-fw#76]
---------------------------------------------------------

feature 请在标题开头加 feature . 并清空本模板的所有内容。

提问题之前请先看是否已经有人提出。凡是发现重复提的问题。一律直接关闭。

只留下一句话简单描述的，除非特别明显的问题，否则一律直接关闭和无视。

---------------------------------------------------------
## 硬件信息
K2P
### 设备厂商：
斐讯
### 设备硬件版本(如A1))：
A1
### 固件版本:

  | 3.4.3.9-099_20171031-0235
-- | --

----------------------------------------------------------

## bug 详情描述：

IPTV 代理服务器设置UDP 代理 (Udpxy):端口后，点击Web status，显示连接失败。Udpxy并未启用
--

## bug 重现具体步骤:

1. 启用组播路由到内网

2. 设置udpxy端口

3. 应用页面设置

### 预期的操作结果：
点击Web status打开Udpxy状态页面

### 实际的操作结果：
点击Web status显示无法连接

**Comment by ihacklog** [comment]
具体是代理哪个地址。你这样说，我这也没法测试。

**Comment by Tulipyun** [comment]
[image: 内嵌图片 1]

灯大您好！

首先我需要的是UDPxy能够正常运行起来，目前点击Web status，是无法打开UDPxy的状态页面的。

PS：我的路由器地址已经换为192.168.1.1，因此浏览器地址栏的地址是正确的。

谢谢！


2017-11-01 19:01 GMT+08:00 荒野无灯 <notifications@github.com>:

**Comment by Tulipyun** [comment]
![default](https://user-images.githubusercontent.com/33225815/32307411-4aaf6f3c-bfbb-11e7-8221-1887188223ac.png)

**Comment by ihacklog** [comment]
IPTV融合进普通网络一般步骤
http://www.right.com.cn/forum/forum.php?mod=viewthread&tid=248400

**Comment by ihacklog** [comment]
padavan配置iptv相关及AP模式开启路由转发
http://jg192.f3322.net:82/wordpress/index.php/2017/06/03/padavan%E9%85%8D%E7%BD%AEiptv%E7%9B%B8%E5%85%B3/

**Comment by ihacklog** [comment]
你这只填写了一个7788 ，能工作 才怪。。。

**Comment by Tulipyun** [comment]
谢谢，试了很多个配置都不行，还是直接用交换机模式把iptv接进来算了。
