### ISSUE TITLE
k2p 去广告插件koolproxy在路由器每次重启后失效

### ISSUE THREAD

**Issue by wyungang** [ihacklog/p4davan-fw#79]
---------------------------------------------------------
k2p 去广告插件koolproxy在路由器每次重启后失效

---------------------------------------------------------
斐讯k2p A1

### 固件版本:K2P_3.4.3.9-099_20171101

----------------------------------------------------------

## bug 重现具体步骤:

1. 开启koolprocy

2. 路由器重启

3. 打开优酷视频

**Comment by ihacklog** [comment]
未按模板规范描述重现bug的具体步骤。且等待长时间之后没有人回复。
本issue直接关闭。
