### ISSUE TITLE
K2P固件能否把阉割的telnet加上呢，我用K2P远程跳管理其他设备

### ISSUE THREAD

**Issue by keboy520** [ihacklog/p4davan-fw#8]
## 固件版本（如3.4.3.9-099_20170905-1100):

3.4.3.9-099_20170715-0204
--

## bug 重现具体步骤:

1. xxxxx

2. xxxxx

3. xxxxx

### 操作预期的结果：
希望增加这个功能

### 操作实际的结果：
能够远程登陆其他设备

**Comment by keboy520** [comment]
K2P

**Comment by ihacklog** [comment]
这个看情况，如果容量允许才行

**Comment by ihacklog** [comment]
已经内置
