### ISSUE TITLE
最新版本网络流量上下行反了！

### ISSUE THREAD

**Issue by jw19891128** [ihacklog/p4davan-fw#82]
---------------------------------------------------------

20171031-0235版本网络流量上下行反了！网络流量里面显示的上行和下行是反的，
---------------------------------------------------------

### 固件版本:20171031-0235

----------------------------------------------------------

## bug 详情描述：

经过反复测速和下载时观察确定，网络流量里面显示的上行和下行是反的，下载时，上行流量曲线达到峰值，上传时，下载流量曲线达到峰值，所以确定上行和下行流量曲线是搞反了，在您的帖子也有不少人反应了，望您有时间改进，上个帖子标题与内容不符，抱歉！

**Comment by ihacklog** [comment]
你去看下Padavan官方的文档，再来提issue好不？
这不是反的。

**Comment by ihacklog** [comment]
上下行是针对接口本身的。
作为路由器的无线interface, 它的下行， 就是你的电脑的上行。
它的上行，就是你的电脑的下行。
所以，padavan没毛病。没反！
