### ISSUE TITLE
led禁用后，还亮着红灯

### ISSUE THREAD

**Issue by wyungang** [ihacklog/p4davan-fw#83]
--------------------------------------------------------
led禁用后，灯是不是应该全部灭掉？现在禁用后还亮红灯。
---------------------------------------------------------

### 固件版本:K2P_3.4.3.9-099_20171101-0426

----------------------------------------------------------

## bug 重现具体步骤:

1. 自定义设置-led事件

2. 启用led 关闭

3. 还亮红灯

**Comment by ihacklog** [comment]
这个。目前，是固件默认行为。有灯主要用来表示路由器开着的状态。

**Comment by ihacklog** [comment]
后期有时间可以考虑优化吧。

**Comment by wyungang** [comment]
那还还是不要改了，习惯就好了

**Comment by nobk** [comment]
我放在卧室的，希望那个红灯也能关掉，有点光污染。

**Comment by wyungang** [comment]
这个可以自己设置，把wan led 和无线led禁用后就不亮了额

**Comment by renyi99** [comment]
网络连接正常，灯也正常。但是网络断掉后，灯就不亮了
