### ISSUE TITLE
feature：能否把2.4g mac地址做成跟官方固件一样的？

### ISSUE THREAD

**Issue by wyungang** [ihacklog/p4davan-fw#84]
因不会插入图片，灯老师请见谅。如下，路由器：斐讯k2p A1版本，分别刷了官方固件和灯老师的老毛子，记录下mac地址。
官方和老毛子的wan、lan、5g是一样的，但是2.4g mac地址第四个字节不一样，能否做成跟官方一样的呢？
官方 
wan | 74 | 7D | 24 | 92 | 9A | 61 |  
lan   | 74 | 7D | 24 | 92 | 9A | 62 |  
5g    | 74 | 7D | 24 | 92 | 9A | 63 |  
2.4g | 76 | 7D | 24  | 92| 9A | 63 |  

老毛子
wan | 74 | 7D | 24 | 92 | 9A | 61 |  
lan   | 74 | 7D | 24 | 92 | 9A | 62 |  
5g    | 74 | 7D | 24 | 92 | 9A | 63 |  
2.4g | 76 | 7D | 24 | A2 | 9A | 63 |

**Comment by mjyhj** [comment]
可以自己到breed里修改2.4G MAC地址

**Comment by ihacklog** [comment]
各个系统实现不同。没有什么关系。
