### ISSUE TITLE
K2P 最新1101版的KP无法过滤HTTPS

### ISSUE THREAD

**Issue by love336** [ihacklog/p4davan-fw#89]
### 固件版本:3.4.3.9-099_20171101-2321

----------------------------------------------------------

## bug 详情描述：
升级了最新版，发现使用KP的用户自定义过滤规则：Custom Rule File "user.txt" 无法过滤HTTPS站点，普通的HTTP和替换规则没问题
另外goolefu开启后，在 Bypass dst IP/domain 输入域名，不起排除效果

## bug 重现具体步骤:

1. 在Custom Rule File "user.txt"里填入规则：https://www.smzdm.com###google_center_div

2. 强制刷新网页没有效果

3. K2P重新刷回0910版，使用相同规则，可以过滤掉该广告

### 预期的操作结果：
能过滤HTTPS站点的广告

### 实际的操作结果：
没有过滤HTTPS站点的广告

**Comment by ihacklog** [comment]
最新版的KP , 对于过滤https 功能有变动。建议你去KP群或论坛问问。

**Comment by ihacklog** [comment]
长期等待无人回复。关闭。
