### ISSUE TITLE
感谢灯大。端口转发、smartdns的问题。

### ISSUE THREAD

**Issue by superliurui** [ihacklog/p4davan-fw#90]
---------------------------------------------------------

感谢灯大。

问题1，端口转发的问题。端口范围：如果填123-456这样的端口范围，则提示不是一个有效的端口号。

问题2，日志里总是提示：smartdns[1984]: incomplete or malformed DNS request。

## 硬件信息

设备：

K2P 银色

设备硬件版本 A1

固件版本: 3.4.3.9-099_20171101-2321

---------------------------------------------------------

----------------------------------------------------------

## bug 重现具体步骤:

1. xxxxx

2. xxxxx

3. xxxxx

**Comment by ihacklog** [comment]
incomplete or malformed DNS request: 我这里从来没有出现。应该是你什么客户端引起的，你排查一下。

**Comment by ihacklog** [comment]
端口填写一个试试啊。。。。

**Comment by superliurui** [comment]
谢谢灯大。单个端口是没问题的。就是端口范围转不了。
