### ISSUE TITLE
feature:建议增加FRP内网穿透

### ISSUE THREAD

**Issue by edgargithub** [ihacklog/p4davan-fw#94]
建议增加FRP内网穿透

**Comment by ihacklog** [comment]
相对 于ngrok的优势在哪？
与固件现在的功能比，增加grp 之后，会有什么改善？

**Comment by pipi55kai** [comment]
请问灯大固件里头的ngrok插件有支持ngrok.cc的打算吗?

**Comment by tuzhis** [comment]
@ihacklog 原理上frp和ngrok一样，frp额外支持udp转发，效率两个不好说，这两个应该是服务端部署了哪个用哪个的关系，移除就不好了

**Comment by qinwei0077** [comment]
frp服务器有一键安装脚本，ngrok设置比较繁琐。

**Comment by MxCen** [comment]
（1）frp 是一个可用于内网穿透的高性能的反向代理应用，支持 tcp, udp, http, https 协议。；
（2）自带Dashboard面板；
（3）相关服务器段软件已经预便于，拿来就可以架设服务器段；（WIN下）
（4）服务器端大流量下不会出现内存泄漏；
（5）frpc 内置了 http proxy 和 socks5 插件，可以使其他机器通过 frpc 的网络访问互联网。

**Comment by yn3010** [comment]
+1，frp服务端搭建相对方便，甚至包括网上大量的免费服务端，dashboard简明好使，ngrok有反馈内存泄漏，frp目前无此问题

**Comment by mjyhj** [comment]
还不如上N2N，N2N是P2P方式，大部分流量只需要客户端之间通信

**Comment by Junec** [comment]
增加frp吧，可以保留ngrok，之前一直用的自建frp，很稳定。

**Comment by ihacklog** [comment]
already implemented.
wait K2P 20180317 version and R6800 20180317
