### ISSUE TITLE
ngrokc的调用方式导致多隧道情况会部分失效

### ISSUE THREAD

**Issue by tuzhis** [ihacklog/p4davan-fw#98]
---------------------------------------------------------
## 硬件信息
全部
### 设备厂商：
全部
### 设备具体型号(如psg1218-k2):
全部
### 设备硬件版本(如A1))：
全部
### 固件版本:
全部

----------------------------------------------------------

## bug 详情描述：
ngrokc配置多个隧道的时候命令应该是
ngrokc -SER[]  -AddTun[隧道1] -AddTun[隧道2]
目前是
ngrokc -SER[]  -AddTun[隧道1]
ngrokc -SER[]  -AddTun[隧道2]
这样会导致两个互相竞争，部分隧道失效

## bug 重现具体步骤:
同时配置http和tcp隧道

### 预期的操作结果：
同时有效

### 实际的操作结果：
http隧道失效，改命令后两个都正常

**Comment by ihacklog** [comment]
这个我有空再看看啊。后面可能引入frp.

**Comment by ihacklog** [comment]
ngrok 在20180317 后的版本中已经去除。现在会以frp替代。
