### ISSUE TITLE
K2P-512 1111版不能识别USB设备

### ISSUE THREAD

**Issue by AyaWenRen** [ihacklog/p4davan-fw#99]
### 固件版本: 3.4.3.9-099_20171111-1738
----------------------------------------------------------
## bug 重现具体步骤:
1. 从910更新到1111
2. 手动双清
3. 插入U盘或移动硬盘

**Comment by ihacklog** [comment]
最新版已经修复。而且。这不叫“USB未识别”。
只是界面没显示。。。
